version: '3'

services:
  backend:
    build: backend
    ports:
      - 8080:80
    volumes:
      - ./backend:/app
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app
